### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by TransonQ** [ahkohd/tauri-macos-menubar-app-example#17]
error: proc macro panicked
  --> src/main.rs:24:14
   |
24 |         .run(tauri::generate_context!())
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: icon /Users/x/Desktop/code/tauri-macos-menubar-app-example/src-tauri/icons/icon.png is not RGBA

error: could not compile `tauri-macos-menubar-app-example` (bin "tauri-macos-menubar-app-example") due to previous error

**Comment by TransonQ** [comment]
I encountered this error. May I ask if there is any way to resolve it?

**Comment by ahkohd** [comment]
Hey there, I have been able to reproduce it. I'm working on a fix.

**Comment by ahkohd** [comment]
I realized I forgot to add a tray icon that should be displayed for the production build. This commit fixes the issue 4f68b247d91d83b38ac1d93cd90341abf0488462.

**Comment by ahkohd** [comment]
Let me know if this solves your problem.

**Comment by TransonQ** [comment]
@ahkohd Thank you, the problem has been resolved. Thank you for providing this demo, it is very helpful for beginners  :)
