### ISSUE TITLE
Automatic detection of Tray icon position

### ISSUE THREAD

**Issue by doroved** [ahkohd/tauri-macos-menubar-app-example#3]
Thanks for this code which allowed me to remove `tauri-plugin-positioner` and save space.
```rs
const OFFSET_X: f64 = 50.0;
const OFFSET_Y: f64 = 20.0;

let window = app_handle.get_window("main").unwrap();

let size = window.inner_size().unwrap();

let half_width = size.width / 2;

let x = x - (half_width as f64) + OFFSET_X;

let y = y + OFFSET_Y;

window.set_position(PhysicalPosition { x, y }).unwrap();
```
I have a few issues/suggestions about NSpanel work, I will gradually report them to you.

**First issue/problem**
If you register a hotkey, start the application, press the hotkey, the panel is displayed in the center of the screen, because positioning is triggered only after clicking on the icon in Tray.
Is it realistic to track the position of the icon in Tray without clicking on it and set the position of the panel relative to it? It is desirable to track constantly, because the icon can be moved to the right/left.

https://github.com/ahkohd/tauri-macos-menubar-app-example/assets/30116541/f60f441e-4bed-4645-bc16-7f0576205c05

**Comment by ahkohd** [comment]
Unfortunately, there isn't a direct method to find your tray icon's position. However, here's a workaround: create a secondary window that appears when you press a hotkey.

**Comment by ahkohd** [comment]
I am curious to know how they implemented it; one possible way is to guess. Most Menubar apps are always at the top-right corner.
