### ISSUE TITLE
closable/minimizable/maximizable/resizable in NSPanel

### ISSUE THREAD

**Issue by doroved** [ahkohd/tauri-macos-menubar-app-example#31]
As far as I know, you can customize controls in NSPanel just like in NSWindow.
Could you please add to the example how to display closable/minimizable/maximizable elements?
And also the implementation of resizable is also interesting.
Thanks)

<img width="103" alt="image" src="https://github.com/ahkohd/tauri-macos-menubar-app-example/assets/30116541/19e12fb3-03ed-4515-8aee-6c802e3b0f3b">

**Comment by ahkohd** [comment]
Add the `const NSResizableWindowMask: i32 = 1 << 3;` style mask to the panel to make the menubar panel resizable.
![image](https://github.com/ahkohd/tauri-macos-menubar-app-example/assets/13041443/5656ee5d-a353-4bb2-985c-bfff82030c06)

**Comment by ahkohd** [comment]
This menubar panel example uses `NSWindowStyleMaskNonactivatingPanel` to prevent the panel from stealing focus from the active window that is not the panel. Given this, using `NSWindowStyleMaskNonactivatingPanel` precludes the panel from having a standard title bar (as the window won't be active, you can't directly interact with the title bar). You will have to add these buttons, and the title bar is usually  See this guide: https://tauri.app/v1/guides/features/window-customization/

**Comment by ahkohd** [comment]
We can add the method to set the minimum size of a panel, i.e., `panel.minSize`, to the `tauri-panel` plugin.

You can create an issue there.
