### ISSUE TITLE
Conflict: acceptFirstMouse + data-tauri-drag-region

### ISSUE THREAD

**Issue by doroved** [ahkohd/tauri-macos-menubar-app-example#54]
In my application, I use the ability to pin a window and I ran into a problem, the cause of which I searched for many hours)

### Make these edits to the code to reproduce the problem.
1. **src/App.tsx** - Add an area for dragging the window
```html
   <h1>Menubar App</h1>
   <div style={{ background: "red", padding: "20px", cursor: "grab" }} data-tauri-drag-region> DRAG ME </div>
```
2. Comment out the line
https://github.com/ahkohd/tauri-macos-menubar-app-example/blob/dff4941d1a7b7304616bddcfd7392fde89e66532/src-tauri/src/fns.rs#L53
3. **tauri.conf.json** - Add `acceptFirstMouse` and `startDragging`
```json
  "tauri": {
    "allowlist": {
      "all": false,
      "window": {
        "startDragging": true
      },
...
    "windows": [
      {
...
        "acceptFirstMouse": true
```
After starting the application, open the application by clicking on the system tray icon, you can drag the window anywhere, then you have to click in the area outside the window, wait a few seconds, then click in the `data-tauri-drag-region`.
It is still unclear what exactly triggers the problem, but you will notice that when you click on the `data-tauri-drag-region` again, the window position will change dramatically.
https://youtu.be/McfLrebxq7I

And if you drag the window to the upper right corner and do the operation described above, the window will disappear altogether, apparently changing its position outside the visibility of the macbook window.
https://youtu.be/vof60XG6Dm4

When using a regular window, without tauri-nspanel with the settings `always_on_top(true)` and `accept_first_mouse(true)` I do not see such a problem.

I hope you will be able to solve this problem and maybe better implement it in **tauri-nspanel** package.

**Comment by ahkohd** [comment]
@doroved, I'm glad you found a workaround to this issue!

**Comment by ahkohd** [comment]
> > @doroved, I'm glad you found a workaround to this issue!
> 
> I think we can close this issue, I described the problem and solution here: [tauri-apps/tauri#6568 (comment)](https://github.com/tauri-apps/tauri/issues/6568#issuecomment-2131272886)
> 
> I don't know if it makes sense to do something for nspanel, it's probably better to wait for the edit to be made on the Tauri side, and if someone encounters this problem now, they can use my solution.

Okay, I'll pin the issue. Thanks!
