### ISSUE TITLE
Tauri v2

### ISSUE THREAD

**Issue by reyamir** [ahkohd/tauri-macos-menubar-app-example#66]
Hi, thank for great example
I wonder how can I implement it for Tauri v2 instead?

**Comment by reyamir** [comment]
I've managed convert to tauri v2

**Comment by constantindjonkam** [comment]
@reyamir Could you pls explain how you migrated to V2?

**Comment by ahkohd** [comment]
Hello, yes thanks for the reminder, i'll create a branch for v2.

**Comment by reyamir** [comment]
> @reyamir Could you pls explain how you migrated to V2?

You can check my app here: https://github.com/lumehq/lume/commit/3a6e6efa1cf54f9ed56f481a66f2502018df3eee#diff-29c3bd86b4866c63512de90592b31f920ce0516b873ac384005abc1ca215a15f

Note: If you set window `decoration = false` you must set `"windowEffects": { "effects": ["sheet"] }` too, if not window will never open

**Comment by ahkohd** [comment]
@constantindjonkam the v2 branch is ready and now the default branch.

Please test and let me know if you encounter any issue.

Thanks,
